// @refresh reset
import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "es" | "en";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  es: {
    // Navbar
    "nav.perfil": "Perfil",
    "nav.experiencia": "Experiencia",
    "nav.habilidades": "Habilidades",
    "nav.websites": "Websites",
    "nav.libros": "Libros",
    "nav.formacion": "Formación",
    "nav.contacto": "Contacto",

    // Hero
    "hero.available": "Disponible para consultoría",
    "hero.subtitle": "MBA - Ingeniero Industrial | Transferencia Tecnológica & Modernización con IA",
    "hero.scroll": "SCROLL",
    "hero.stat1": "Años de Experiencia",
    "hero.stat2": "Años Dirección",
    "hero.stat3": "Países",
    "hero.stat4": "Proyectos",
    "hero.tagline": "// WR. MBA · ING. INDUSTRIAL",

    // Profile
    "profile.section": "01 // PERFIL",
    "profile.title": "Perfil Profesional",
    "profile.p1": "Ingeniero Industrial con más de 30 años de experiencia en dirección técnica, gestión industrial, control de calidad y ejecución de proyectos de infraestructura y manufactura, incluyendo contratos gubernamentales internacionales.",
    "profile.p2": "Parte del equipo de proyectos de energía e industria, evaluación técnica de contratos públicos, gestión ISO 9000, como CAD manager y también jefe de producción de planta industrial, innovación productiva para MYPES e implementación de inteligencia artificial en procesos administrativos.",
    "profile.intl": "Experiencia Internacional",
    "profile.h1": "Proyectos hidroenergéticos en Perú",
    "profile.h2": "Manufactura industrial en EE.UU.",
    "profile.h3": "Gestión de producción y calidad",
    "profile.h4": "Consultoría técnica internacional",

    // Experience
    "exp.section": "02 // EXPERIENCIA",
    "exp.title": "Trayectoria Profesional",
    "exp.1.title": "CEO – Ozonomach",
    "exp.1.company": "Lima, Perú | Cargo de Dirección Ejecutiva",
    "exp.1.f1": "Dirección estratégica empresarial",
    "exp.1.f2": "Gestión de innovación y desarrollo de producto",
    "exp.1.f3": "Toma de decisiones financieras y operativas",
    "exp.1.f4": "Implementación de automatización con IA",
    "exp.1.f5": "Gestión de compras internacionales",
    "exp.2.title": "Docente en Escuelas en China",
    "exp.2.company": "Younuvo Jilin Educational Experts – Changchun, China",
    "exp.2.f1": "Profesor de inglés y cultura occidental en seis escuelas y universidad, con 25 horas de clases semanales para aproximadamente 1,000 alumnos durante 1 año",
    "exp.3.title": "Consultor de Ingeniería",
    "exp.3.company": "Freelance, Nueva York, EE. UU.",
    "exp.3.f1": "Asistencia en proyectos de invenciones domésticas",
    "exp.3.f2": "Planos de ingeniería para fabricación en el mercado estadounidense y chino",
    "exp.3.f3": "Apoyo en adquisiciones para encontrar proveedores a nivel mundial",
    "exp.4.title": "Asistente de Ingeniería / Programador CNC",
    "exp.4.company": "Millwork NARVA – Springfield, NJ, EE. UU.",
    "exp.4.f1": "Diseño de más de 100 paneles 3D para postprocesamiento en G-code con Biese Rover y Holzher Linx",
    "exp.4.f2": "Desarrollo de nuevos productos como paneles de pared 3D, pantallas y esculturas en alto relieve utilizando Aspire",
    "exp.4.f3": "Dibujo de gabinetes en formatos SolidWorks y AutoCAD para fabricación",
    "exp.4.f4": "Elaboración de planos de taller (shop drawings)",
    "exp.5.title": "Jefe de Planta",
    "exp.5.company": "MAJESTIC Industry – NJ, USA",
    "exp.5.f1": "Dirección de planta industrial",
    "exp.5.f2": "Gestión de personal",
    "exp.5.f3": "Diseño de layout industrial",
    "exp.5.f4": "Control de calidad y mejora de procesos",
    "exp.6.title": "Project Manager – Contratos Gobierno",
    "exp.6.company": "Mechanical Factory O-AVIATION, New Jersey, USA",
    "exp.6.f1": "Supervisión de cumplimiento contractual",
    "exp.6.f2": "Coordinación de equipos técnicos",
    "exp.6.f3": "Control de estándares ISO",
    "exp.6.f4": "Gestión de calidad bajo especificaciones militares",
    "exp.7.title": "Jefe CAD / ISO 9000 Auditor",
    "exp.7.company": "LAHMEYER WATER & ENERGY, Lima, Perú",
    "exp.7.f1": "Coordinación multidisciplinaria en proyectos hidroenergéticos",
    "exp.7.f2": "Gestión documental técnica",
    "exp.7.f3": "Supervisión de estándares de calidad",
    "exp.7.f4": "Implementación de base de datos técnica",

    // Skills
    "skills.section": "03 // COMPETENCIAS",
    "skills.title": "Habilidades Técnicas",
    "skills.ai": "Inteligencia Artificial",
    "skills.cad": "Diseño & CAD",
    "skills.industrial": "Gestión Industrial",
    "skills.trade": "Comercio Internacional",
    "skills.management": "Competencias Directivas",
    "skills.software": "Software & Tools",
    "skills.tag.univ": "Articulación Universidad-Empresa",
    "skills.tag.innov": "Innovación Productiva",
    "skills.tag.eval": "Evaluación de Contratos",
    "skills.tag.modern": "Modernización con IA",

    // Websites
    "web.section": "04 // WEB PROPERTIES",
    "web.title": "Propietario de Sitios Web",
    "web.gestion": "Gestión Proyectos",

    // Books
    "books.section": "05 // PUBLICACIONES",
    "books.title": "Proyectos de Libros",
    "books.1.cover": "Inteligencia Artificial",
    "books.1.title": "Electicismo IA: la llave de un desarrollo postergado",
    "books.1.subtitle": "Una visión transformadora para América Latina",
    "books.1.desc": "Explora cómo la inteligencia artificial puede ser el catalizador que América Latina necesita para cerrar brechas históricas de desarrollo, modernizar sus estructuras productivas y competir en la economía global del siglo XXI.",
    "books.1.tag1": "Inteligencia Artificial",
    "books.1.tag2": "Desarrollo",
    "books.2.cover": "Geopolítica Global",
    "books.2.title": "China, el universo que está enseñando a Occidente",
    "books.2.subtitle": "Lecciones de una civilización milenaria",
    "books.2.desc": "Un análisis profundo sobre las lecciones que el modelo de desarrollo chino ofrece a Occidente, desde su enfoque en la planificación estratégica de largo plazo hasta su integración de tecnología y tradición en la construcción de una superpotencia moderna.",
    "books.2.tag1": "China",
    "books.2.tag2": "Occidente",

    // Papers
    "nav.papers": "Papers",
    "papers.section": "05.1 // PAPERS",
    "papers.title": "Publicaciones Académicas",
    "papers.1.title": "Sistemas de Manufactura Circular con IA: Guía de Desensamblaje por Visión, Trazabilidad Eco-QR y Soporte de Decisión Inteligente",
    "papers.1.s1.heading": "1. Introducción",
    "papers.1.s1.content": "La creciente demanda de sistemas industriales sostenibles impulsa la transición de modelos de producción lineales hacia paradigmas de manufactura circular. Esta investigación propone un marco integrado que combina inteligencia artificial (IA), visión por computadora, diseño para desensamblaje y sistemas de trazabilidad digital para apoyar la toma de decisiones inteligentes en sistemas híbridos de manufactura–remanufactura.",
    "papers.1.s2.heading": "2. Problema de Investigación",
    "papers.1.s2.content": "Los sistemas actuales carecen de guía adaptativa de desensamblaje, evaluación en tiempo real de la condición del producto y marcos de decisión integrados. Esta investigación aborda estas brechas mediante herramientas habilitadas por IA que conectan diseño, desensamblaje y toma de decisiones.",
    "papers.1.s3.heading": "3. Objetivos de Investigación",
    "papers.1.s3.content": "El objetivo es desarrollar un marco impulsado por IA que apoye decisiones de enrutamiento, elecciones de reparación vs. remanufactura, identificación de materiales y trazabilidad del ciclo de vida utilizando sistemas Eco-QR y aplicaciones basadas en visión.",
    "papers.1.s4.heading": "4. Metodología",
    "papers.1.s4.content": "La metodología integra visión por computadora, aprendizaje automático, modelos de optimización, principios de diseño para desensamblaje y sistemas de trazabilidad digital. Una base de datos estructurada de material-proceso apoyará la toma de decisiones y aplicaciones industriales.",
    "papers.1.s5.heading": "5. Contribuciones Esperadas",
    "papers.1.s5.content": "Los resultados esperados incluyen un sistema de desensamblaje basado en visión, un marco de trazabilidad Eco-QR, modelos de soporte de decisión con IA y una base de datos de inteligencia material-proceso.",
    "papers.1.s6.heading": "6. Impacto",
    "papers.1.s6.content": "Esta investigación contribuye a reducir los residuos industriales, mejorar la eficiencia de remanufactura y habilitar sistemas de economía circular alineados con estándares de sostenibilidad.",
    "papers.1.s7.heading": "7. Alineación",
    "papers.1.s7.content": "La investigación se alinea con el enfoque de NTNU en manufactura sostenible, sistemas industriales y transformación digital.",
    "papers.2.title": "EcoLifeTwin – Un Gemelo Digital Multimodal para Simular la Vida Diaria en una Economía Circular Impulsada por IA",
    "papers.2.s1.heading": "1. Resumen",
    "papers.2.s1.content": "EcoLifeTwin es un gemelo digital multimodal centrado en el ser humano que simula rutinas cotidianas dentro de un sistema de producción-logística de ciclo cerrado. Integra simulación de eventos discretos, aprendizaje por refuerzo y visualización en tiempo real para demostrar cómo la IA puede gestionar autónomamente el ciclo de vida de productos eco-amigables, desde la fabricación y uso hasta el retorno, reciclaje y remanufactura, optimizando la logística y minimizando el impacto ambiental.",
    "papers.2.s2.heading": "2. Concepto",
    "papers.2.s2.content": "El modelo crea una familia virtual viviendo su rutina diaria (desayuno, desplazamientos, compras, eliminación de residuos) en una ciudad inteligente y sostenible. Agentes de IA toman decisiones en tiempo real sobre reciclaje, remanufactura y rutas de recolección, mostrando potenciales reducciones de hasta 40% en residuos materiales preservando la calidad de vida.",
    "papers.2.s3.heading": "3. Tecnologías",
    "papers.2.s3.content": "Simulación con Python + SimPy; modelado basado en agentes y aprendizaje por refuerzo con Mesa / Gymnasium; visualización con Streamlit + Matplotlib y Unity (planificado); IA con scikit-learn + TensorFlow; datos públicos de reciclaje y emisiones.",
    "papers.2.s4.heading": "4. Alineación con Industria 5.0",
    "papers.2.s4.content": "El proyecto apoya directamente los principios de Industria 5.0 y extiende la investigación del grupo de Logística de Producción de KTH, particularmente en 'Logística de producción habilitando la circularidad'. Métricas de sostenibilidad como emisiones de CO₂, reducción de residuos materiales y costo logístico se visualizan en vivo.",
    "papers.2.s5.heading": "5. Estado y Recursos",
    "papers.2.s5.content": "En desarrollo activo – Lanzamiento público planificado para mayo de 2026. Código disponible en github.com/warp2121/EcoLifeTwin y demo cyberpunk en vivo en eco-life-twin.vercel.app.",
    "papers.2.s6.heading": "6. Trabajos Relacionados",
    "papers.2.s6.content": "Este proyecto se basa en: Jeong et al. (2020) – Diseño de Gemelos Digitales para Apoyar la Toma de Decisiones en Logística de Producción; y Klein et al. (2026) – Hacia la Logística de Producción Auto-Organizada en Fábricas Circulares.",

    // Education
    "edu.section": "06 // FORMACIÓN",
    "edu.title": "Educación & Idiomas",
    "edu.mba.tag": "MBA",
    "edu.mba.degree": "Master of Business Administration",
    "edu.mba.school": "Webber International University, Florida, USA",
    "edu.eng.tag": "INGENIERÍA",
    "edu.eng.degree": "Ingeniero Industrial",
    "edu.eng.school": "Universidad Inca Garcilaso de la Vega, Perú",
    "edu.lang.es": "Español",
    "edu.lang.es.level": "Nativo",
    "edu.lang.en": "English",
    "edu.lang.en.level": "Avanzado",
    "edu.lang.zh": "Chinese",
    "edu.lang.zh.level": "En progreso",
    "edu.lang.de": "German",
    "edu.lang.de.level": "En progreso",

    // Contact
    "contact.section": "07 // CONTACTO",
    "contact.title": "Construyamos el futuro juntos",
    "contact.desc": "Especializado en transferencia tecnológica, modernización productiva con IA y gestión de proyectos internacionales.",
    "contact.cv": "Descargar CV",
    "contact.footer": "Lima, Perú — Disponible para proyectos remotos e internacionales",

    // Footer
    "footer.line1": "Walter Ramírez — MBA, Ingeniero Industrial",
    "footer.line2": "Transferencia Tecnológica & Modernización Productiva con IA",

    // Leyes Tech
    "leyes.download.png": "⬇ DESCARGAR PNG",
    "leyes.download.doc": "⬇ DESCARGAR DOC",
    "leyes.close": "✕ CERRAR",
    "leyes.executive": "// Documento Ejecutivo",
    "leyes.heading1": "Resumen Ejecutivo:",
    "leyes.heading2": "Agenda de Modernización del Perú",
    "leyes.card1.title": "Perfil del Consultor Técnico",
    "leyes.card1.p1": "Ing. Ind. Walter Ramírez, ",
    "leyes.card1.p1b": "MBA (Florida, USA)",
    "leyes.card1.p2a": "Más de ",
    "leyes.card1.p2b": "30 años de experiencia internacional",
    "leyes.card1.p2c": " dividido en proyectos de infraestructura, diseño, manufactura y gestión de contratos, compras, docencia en Perú, EE.UU. y China.",
    "leyes.card1.p3a": "Experto en auditoría ",
    "leyes.card1.p3b": "ISO 9000",
    "leyes.card1.p3c": " y aplicación de ",
    "leyes.card1.p3d": "CAD e IA",
    "leyes.card1.p3e": " para la eficiencia gubernamental.",
    "leyes.card2.title": "Diagnóstico Crítico",
    "leyes.card2.l1a": "Pérdida por Corrupción: ",
    "leyes.card2.l1b": "~10%",
    "leyes.card2.l1c": " del presupuesto anual.",
    "leyes.card2.l2a": "Ineficiencia en Obras: ",
    "leyes.card2.l2b": "~30%",
    "leyes.card2.l2c": " con sobrecostos y baja durabilidad.",
    "leyes.card2.l3a": "Baja Competitividad: ",
    "leyes.card2.l3b": "Escasa integración con mercados masivos (China/India).",
    "leyes.card3.title": "Propuestas de Ley — 1er Año de Legislatura",
    "leyes.card3.law1": "Ley de Trazabilidad Blockchain",
    "leyes.card3.law1.desc": "Registro inmutable de contratos y auditoría en tiempo real para eliminar la manipulación.",
    "leyes.card3.law2": "Ley de Estándares de Construcción",
    "leyes.card3.law2.desc": "Garantizar una vida útil mínima de 20–30 años mediante supervisión digital obligatoria.",
    "leyes.card3.law3": "Ley de Movilidad Sostenible",
    "leyes.card3.law3.desc": "Infraestructura segregada para transporte eléctrico y bicicletas para reducir el tráfico.",
    "leyes.card3.law4": "Ley Marketplace Perú Global",
    "leyes.card3.law4.desc": "Plataforma estatal para exportación directa, facilitando el acceso a mercados globales.",
    "leyes.card4.title": "Recomendaciones Estratégicas — Primeros 6–12 meses",
    "leyes.card4.r1": "Implementar pilotos regionales de bajo costo para demostrar resultados rápidos en transparencia.",
    "leyes.card4.r2": "Priorizar la participación en comisiones de Fiscalización o Transportes para liderar la agenda técnica.",
    "leyes.card4.r3": "Fomentar Alianzas Público-Privadas para el financiamiento de la modernización tecnológica.",
    "leyes.footer": "// AGENDA DE MODERNIZACIÓN DEL PERÚ",
  },
  en: {
    // Navbar
    "nav.perfil": "Profile",
    "nav.experiencia": "Experience",
    "nav.habilidades": "Skills",
    "nav.websites": "Websites",
    "nav.libros": "Books",
    "nav.formacion": "Education",
    "nav.contacto": "Contact",

    // Hero
    "hero.available": "Available for consulting",
    "hero.subtitle": "MBA - Industrial Engineer | Technology Transfer & AI Modernization",
    "hero.scroll": "SCROLL",
    "hero.stat1": "Years of Experience",
    "hero.stat2": "Years in Management",
    "hero.stat3": "Countries",
    "hero.stat4": "Projects",
    "hero.tagline": "// WR. MBA · INDUSTRIAL ENGINEER",

    // Profile
    "profile.section": "01 // PROFILE",
    "profile.title": "Professional Profile",
    "profile.p1": "Industrial Engineer with over 30 years of experience in technical management, industrial management, quality control, and execution of infrastructure and manufacturing projects, including international government contracts.",
    "profile.p2": "Part of the team on energy and industry projects, technical evaluation of public contracts, ISO 9000 management, as CAD manager and also production manager of an industrial plant, productive innovation for SMEs, and implementation of artificial intelligence in administrative processes.",
    "profile.intl": "International Experience",
    "profile.h1": "Hydropower projects in Peru",
    "profile.h2": "Industrial manufacturing in the USA",
    "profile.h3": "Production and quality management",
    "profile.h4": "International technical consulting",

    // Experience
    "exp.section": "02 // EXPERIENCE",
    "exp.title": "Professional Career",
    "exp.1.title": "CEO – Ozonomach",
    "exp.1.company": "Lima, Peru | Executive Management Position",
    "exp.1.f1": "Strategic business management",
    "exp.1.f2": "Innovation management and product development",
    "exp.1.f3": "Financial and operational decision-making",
    "exp.1.f4": "AI automation implementation",
    "exp.1.f5": "International procurement management",
    "exp.2.title": "Teacher at Schools in China",
    "exp.2.company": "Younuvo Jilin Educational Experts – Changchun, China",
    "exp.2.f1": "English and Western culture teacher at six schools and a university, with 25 weekly class hours for approximately 1,000 students over 1 year",
    "exp.3.title": "Engineering Consultant",
    "exp.3.company": "Freelance, New York, USA",
    "exp.3.f1": "Assistance in domestic invention projects",
    "exp.3.f2": "Engineering blueprints for manufacturing in the American and Chinese markets",
    "exp.3.f3": "Procurement support to find suppliers worldwide",
    "exp.4.title": "Engineering Assistant / CNC Programmer",
    "exp.4.company": "Millwork NARVA – Springfield, NJ, USA",
    "exp.4.f1": "Design of over 100 3D panels for G-code post-processing with Biese Rover and Holzher Linx",
    "exp.4.f2": "Development of new products such as 3D wall panels, screens, and high-relief sculptures using Aspire",
    "exp.4.f3": "Cabinet drawing in SolidWorks and AutoCAD formats for manufacturing",
    "exp.4.f4": "Preparation of shop drawings",
    "exp.5.title": "Plant Manager",
    "exp.5.company": "MAJESTIC Industry – NJ, USA",
    "exp.5.f1": "Industrial plant management",
    "exp.5.f2": "Personnel management",
    "exp.5.f3": "Industrial layout design",
    "exp.5.f4": "Quality control and process improvement",
    "exp.6.title": "Project Manager – Government Contracts",
    "exp.6.company": "Mechanical Factory O-AVIATION, New Jersey, USA",
    "exp.6.f1": "Contract compliance supervision",
    "exp.6.f2": "Technical team coordination",
    "exp.6.f3": "ISO standards control",
    "exp.6.f4": "Quality management under military specifications",
    "exp.7.title": "CAD Manager / ISO 9000 Auditor",
    "exp.7.company": "LAHMEYER WATER & ENERGY, Lima, Peru",
    "exp.7.f1": "Multidisciplinary coordination in hydropower projects",
    "exp.7.f2": "Technical document management",
    "exp.7.f3": "Quality standards supervision",
    "exp.7.f4": "Technical database implementation",

    // Skills
    "skills.section": "03 // SKILLS",
    "skills.title": "Technical Skills",
    "skills.ai": "Artificial Intelligence",
    "skills.cad": "Design & CAD",
    "skills.industrial": "Industrial Management",
    "skills.trade": "International Trade",
    "skills.management": "Management Skills",
    "skills.software": "Software & Tools",
    "skills.tag.univ": "University-Industry Articulation",
    "skills.tag.innov": "Productive Innovation",
    "skills.tag.eval": "Contract Evaluation",
    "skills.tag.modern": "AI Modernization",

    // Websites
    "web.section": "04 // WEB PROPERTIES",
    "web.title": "Website Owner",
    "web.gestion": "Project Management",

    // Books
    "books.section": "05 // PUBLICATIONS",
    "books.title": "Book Projects",
    "books.1.cover": "Artificial Intelligence",
    "books.1.title": "AI: The Key to a Delayed Development",
    "books.1.subtitle": "A Transformative Vision for Latin America",
    "books.1.desc": "Explores how artificial intelligence can be the catalyst Latin America needs to close historical development gaps, modernize its productive structures, and compete in the 21st-century global economy.",
    "books.1.tag1": "Artificial Intelligence",
    "books.1.tag2": "Development",
    "books.2.cover": "Global Geopolitics",
    "books.2.title": "China, the Universe Teaching the West",
    "books.2.subtitle": "Lessons from a Millennial Civilization",
    "books.2.desc": "A deep analysis of the lessons China's development model offers the West, from its long-term strategic planning approach to its integration of technology and tradition in building a modern superpower.",
    "books.2.tag1": "China",
    "books.2.tag2": "The West",

    // Papers
    "nav.papers": "Papers",
    "papers.section": "05.1 // PAPERS",
    "papers.title": "Academic Publications",
    "papers.1.title": "AI-Enabled Circular Manufacturing Systems: Vision-Based Disassembly Guidance, Eco-QR Traceability, and Intelligent Decision Support",
    "papers.1.s1.heading": "1. Introduction",
    "papers.1.s1.content": "The increasing demand for sustainable industrial systems is driving the transition from linear production models toward circular manufacturing paradigms. This research proposes an integrated framework combining artificial intelligence (AI), computer vision, design for disassembly, and digital traceability systems to support intelligent decision-making in hybrid manufacturing–remanufacturing systems.",
    "papers.1.s2.heading": "2. Research Problem",
    "papers.1.s2.content": "Current systems lack adaptive disassembly guidance, real-time evaluation of product condition, and integrated decision frameworks. This research addresses these gaps through AI-enabled tools that connect design, disassembly, and decision-making.",
    "papers.1.s3.heading": "3. Research Objectives",
    "papers.1.s3.content": "The objective is to develop an AI-driven framework supporting routing decisions, repair vs remanufacturing choices, material identification, and lifecycle traceability using Eco-QR systems and vision-based applications.",
    "papers.1.s4.heading": "4. Methodology",
    "papers.1.s4.content": "The methodology integrates computer vision, machine learning, optimization models, design for disassembly principles, and digital traceability systems. A structured material-process database will support decision-making and industrial applications.",
    "papers.1.s5.heading": "5. Expected Contributions",
    "papers.1.s5.content": "Expected outputs include a vision-based disassembly system, Eco-QR traceability framework, AI decision-support models, and a material-process intelligence database.",
    "papers.1.s6.heading": "6. Impact",
    "papers.1.s6.content": "This research contributes to reducing industrial waste, improving remanufacturing efficiency, and enabling circular economy systems aligned with sustainability standards.",
    "papers.1.s7.heading": "7. Alignment",
    "papers.1.s7.content": "The research aligns with NTNU's focus on sustainable manufacturing, industrial systems, and digital transformation.",
    "papers.2.title": "EcoLifeTwin – A Multimodal Digital Twin for Simulating Daily Life in an AI-Driven Circular Economy",
    "papers.2.s1.heading": "1. Abstract",
    "papers.2.s1.content": "EcoLifeTwin is a human-centric multimodal digital twin that simulates everyday routines within a closed-loop production-logistics system. By integrating discrete-event simulation, reinforcement learning, and real-time visualization, the framework demonstrates how AI can autonomously manage the lifecycle of eco-friendly products — from manufacturing and use to return, recycling, and remanufacturing — while optimizing logistics and minimizing environmental impact.",
    "papers.2.s2.heading": "2. Concept",
    "papers.2.s2.content": "The model creates a virtual family living its daily routine (breakfast, commuting, shopping, waste disposal) in a smart sustainable city. AI agents make real-time decisions on recycling, remanufacturing, and collection routes, showing potential reductions of up to 40% in material waste while preserving quality of life.",
    "papers.2.s3.heading": "3. Technologies",
    "papers.2.s3.content": "Simulation with Python + SimPy; agent-based modeling and reinforcement learning with Mesa / Gymnasium; visualization with Streamlit + Matplotlib and Unity (planned); AI with scikit-learn + TensorFlow; public recycling and emission datasets.",
    "papers.2.s4.heading": "4. Industry 5.0 Alignment",
    "papers.2.s4.content": "The project directly supports Industry 5.0 principles and extends the KTH Production Logistics group research, particularly 'Production logistics enabling circularity'. Sustainability metrics such as CO₂ emissions, material waste reduction, and logistics cost are visualized live.",
    "papers.2.s5.heading": "5. Status & Resources",
    "papers.2.s5.content": "In active development – Public release planned for May 2026. Code available at github.com/warp2121/EcoLifeTwin and live cyberpunk demo at eco-life-twin.vercel.app.",
    "papers.2.s6.heading": "6. Related Work",
    "papers.2.s6.content": "This project builds upon: Jeong et al. (2020) – A Design of Digital Twins for Supporting Decision-Making in Production Logistics; and Klein et al. (2026) – Toward Self-Organizing Production Logistics in Circular Factories.",

    // Education
    "edu.section": "06 // EDUCATION",
    "edu.title": "Education & Languages",
    "edu.mba.tag": "MBA",
    "edu.mba.degree": "Master of Business Administration",
    "edu.mba.school": "Webber International University, Florida, USA",
    "edu.eng.tag": "ENGINEERING",
    "edu.eng.degree": "Industrial Engineer",
    "edu.eng.school": "Universidad Inca Garcilaso de la Vega, Peru",
    "edu.lang.es": "Spanish",
    "edu.lang.es.level": "Native",
    "edu.lang.en": "English",
    "edu.lang.en.level": "Advanced",
    "edu.lang.zh": "Chinese",
    "edu.lang.zh.level": "In progress",
    "edu.lang.de": "German",
    "edu.lang.de.level": "In progress",

    // Contact
    "contact.section": "07 // CONTACT",
    "contact.title": "Let's build the future together",
    "contact.desc": "Specialized in technology transfer, AI-driven productive modernization, and international project management.",
    "contact.cv": "Download CV",
    "contact.footer": "Lima, Peru — Available for remote and international projects",

    // Footer
    "footer.line1": "Walter Ramírez — MBA, Industrial Engineer",
    "footer.line2": "Technology Transfer & AI-Driven Productive Modernization",

    // Leyes Tech
    "leyes.download.png": "⬇ DOWNLOAD PNG",
    "leyes.download.doc": "⬇ DOWNLOAD DOC",
    "leyes.close": "✕ CLOSE",
    "leyes.executive": "// Executive Document",
    "leyes.heading1": "Executive Summary:",
    "leyes.heading2": "Peru Modernization Agenda",
    "leyes.card1.title": "Technical Consultant Profile",
    "leyes.card1.p1": "Ind. Eng. Walter Ramírez, ",
    "leyes.card1.p1b": "MBA (Florida, USA)",
    "leyes.card1.p2a": "Over ",
    "leyes.card1.p2b": "30 years of international experience",
    "leyes.card1.p2c": " spanning infrastructure projects, design, manufacturing, and contract management, procurement, and teaching in Peru, USA, and China.",
    "leyes.card1.p3a": "Expert in ",
    "leyes.card1.p3b": "ISO 9000",
    "leyes.card1.p3c": " auditing and application of ",
    "leyes.card1.p3d": "CAD & AI",
    "leyes.card1.p3e": " for government efficiency.",
    "leyes.card2.title": "Critical Diagnosis",
    "leyes.card2.l1a": "Corruption Loss: ",
    "leyes.card2.l1b": "~10%",
    "leyes.card2.l1c": " of the annual budget.",
    "leyes.card2.l2a": "Construction Inefficiency: ",
    "leyes.card2.l2b": "~30%",
    "leyes.card2.l2c": " with cost overruns and low durability.",
    "leyes.card2.l3a": "Low Competitiveness: ",
    "leyes.card2.l3b": "Limited integration with massive markets (China/India).",
    "leyes.card3.title": "Law Proposals — 1st Year of Legislature",
    "leyes.card3.law1": "Blockchain Traceability Law",
    "leyes.card3.law1.desc": "Immutable contract registry and real-time auditing to eliminate manipulation.",
    "leyes.card3.law2": "Construction Standards Law",
    "leyes.card3.law2.desc": "Guarantee a minimum lifespan of 20–30 years through mandatory digital supervision.",
    "leyes.card3.law3": "Sustainable Mobility Law",
    "leyes.card3.law3.desc": "Segregated infrastructure for electric transport and bicycles to reduce traffic.",
    "leyes.card3.law4": "Peru Global Marketplace Law",
    "leyes.card3.law4.desc": "Government platform for direct exports, facilitating access to global markets.",
    "leyes.card4.title": "Strategic Recommendations — First 6–12 months",
    "leyes.card4.r1": "Implement low-cost regional pilots to demonstrate quick results in transparency.",
    "leyes.card4.r2": "Prioritize participation in Oversight or Transportation committees to lead the technical agenda.",
    "leyes.card4.r3": "Foster Public-Private Partnerships for financing technological modernization.",
    "leyes.footer": "// PERU MODERNIZATION AGENDA",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("es");
  const t = (key: string) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
